micronaut:
  application:
    name: micronautDataListeners
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true