CREATE TABLE table_a (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    column_a VARCHAR(255) NULL,
    column_b VARCHAR(255) NULL
);

CREATE TABLE table_b (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    column_a VARCHAR(255) NULL,
    column_b VARCHAR(255) NULL
);